config/routes.rb
Eidola::Application.routes.draw do
  resources :news

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users

  resources :artists

  resources :releases do
    get :autocomplete_artist_name, :on => :collection
  end

  root :to => "news#index"

end

app/controllers/releases_controller.rb
class ReleasesController < ApplicationController
  skip_before_filter :authorize, only: [:index, :show]
  autocomplete :artist, :name
  
  # GET /releases
  # GET /releases.json
  def index
    @releases = Release.published.paginate(:page => params[:page], :per_page => 9)
    @releases_all = Release.paginate(:page => params[:page], :per_page => 25)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @releases }
    end
  end

  # GET /releases/1
  # GET /releases/1.json
  def show
    @release = Release.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @release }
    end
  end

  # GET /releases/new
  # GET /releases/new.json
  def new
    @release = Release.new
    @artists = Artist.order(:name)
    1.times { @release.tracks.build }
    respond_to do |format| 
      format.html # new.html.erb
      format.json { render json: @release }
    end
  end

  # GET /releases/1/edit
  def edit
    @release = Release.find(params[:id])
  end

  # POST /releases
  # POST /releases.json
  def create
    @release = Release.new(params[:release])
    
    respond_to do |format|
      if @release.save
        @release.tag_tracks
        @release.add_default_zip
        format.html { redirect_to @release, notice: 'Release was successfully created.' }
        format.json { render json: @release, status: :created, location: @release }
      else
        format.html { render action: "new" }
        format.json { render json: @release.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /releases/1
  # PUT /releases/1.json
  def update
    @release = Release.find(params[:id])
    
    respond_to do |format|
      if @release.update_attributes(params[:release])
        @release.tag_tracks
        @release.add_default_zip
        format.html { redirect_to @release, notice: 'Release was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @release.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /releases/1
  # DELETE /releases/1.json
  def destroy
    @release = Release.find(params[:id])
    @release.destroy

    respond_to do |format|
      format.html { redirect_to releases_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/releases_helper.rb
module ReleasesHelper
end

app/views/releases/_form.html.erb
<%= form_for @release, :html => { :multipart => true, :role => 'form' } do |f| %>
  <% if @release.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@release.errors.count, "error") %> prohibited this release from being saved:</h2>

      <ul>
      <% @release.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :artist_name %><br />
    <%= f.autocomplete_field :artist_name, autocomplete_artist_name_releases_path, 'data-delimiter' => ',', :multiple => true, :class => "form-control" %>
    <div id="store"></div>
  </div>
  <div class="form-group">
    <%= f.label :description %><br />
    <%= f.text_area :description, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :date %><br />
    <%= f.date_select :date, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.fields_for :tracks do |t| %>
      <%= render 'track_fields', :f => t %>
    <% end %>
    <%= link_to_add_fields "Add Track", f, :tracks %>
  </div>
  <div class="form-group">
    <%= f.label :cover %>
    <%= image_tag(@release.cover.url(:thumb)) %>
    <%= f.file_field :cover, :class => "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/releases/_grid.html.erb
<% f.each do |release| %>
<div class="release">
  <%= link_to release, :title=> release.title, :class => 'white' do %>
  <h1>
    <%= release.title %><br/>
    <% release.artists.each do |artist| %>
    <%= artist.name %>
    <% end %>
  </h1>
  <%= image_tag(release.cover.url(:thumb)) %>
  <% end %>
</div>    
<% end %>

app/views/releases/_table.html.erb
<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <td>Title</td>
      <td>Publication Date</td>
      <td>Controls</td>
    <tr>
  </thead>
  <tbody>
    <% f.each do |release| %>
    <tr>
      <td><%= release.title %></td>
      <td><%= release.date %></td>
      <td>
	<%= link_to 'Edit', edit_release_path(release), :class => "btn" %>
	<%= link_to 'Destroy', release, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn" %>
	<%= link_to 'Show', release, :class => "btn" %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/releases/_track_fields.html.erb
<div class="track form-group">
  <%= f.label :title %><br />
  <%= f.text_field :title , :class => "form-control" %><br />
  <%= f.label :number %><br />
  <%= f.text_field :number, :class => "form-control" %><br />
  <%= f.label :file %><br />
  <%= f.file_field :file, :class => "form-control" %>
  <%= link_to_remove_fields "remove", f %>
</div>

app/views/releases/edit.html.erb
<h1>Editing release</h1>

<%= render 'form' %>

<%= link_to 'Show', @release %> |
<%= link_to 'Back', releases_path %>

app/views/releases/index.html.erb
<% title "RELEASES" %>
<h1>RELEASES</h1>
<div id="releases">
  <% if session[:user_id] %>    
  <% render 'table', :f => @releases_all %>
  <%= link_to 'New Release', new_release_path, :class => "btn" %>
  <p><%= will_paginate @releases_all %></p>
  <% else %>
  <% render 'grid', :f => @releases %>
  <p><%= will_paginate @releases %></p>
  <% end %>
</div>

app/views/releases/new.html.erb
<h1>New release</h1>

<%= render 'form' %>

<%= link_to 'Back', releases_path %>

app/views/releases/show.html.erb
<% if @release.published? || session[:user_id] %>
<% title @release.title %>
<p id="notice"><%= notice %></p>
<div id="content">
  <div id="release">
    <div class="title">
      <h1><%= @release.title %></h1>
    </div>
    <div class="row">
      <div class="left-col">
      <ul class="artists">
	<% @release.artists.each do |artist| %>
	<li class="artist"><%= link_to artist.name, artist, :class => 'white' %></li>
	<% end %>
      </ul>
      
      <div class="dropdown download-link">
	<button type="button" class="btn dropdown-toggle" data-toggle="dropdown">
	  Download <span class="caret"></span>
	</button>
	<ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
	  <li><%= link_to 'WAV', @release.zip.url %></li>
	  <li><%= link_to 'OGG', @release.zip.url(:ogg) %></li>
	  <li><%= link_to 'MP3', @release.zip.url(:mp3) %></li>
	</ul>
      </div>
      
      </div>
      <%= image_tag(@release.cover.url(:thumb)) %>
      <table class="tracks">
	<thead>
	  <tr>
	    <td>#</td>
	    <td>Title</td>
	    <td>Stream</td>
	  </tr>
	</thead>
	<tbody>
	  <% @release.tracks.each do | track | %>
	  <tr>
	    <td><%= track.number %></td>
	    <td><%= track.title %></td>
	    <td>
	      <audio controls>
		<source src="<%= track.file.url(:mp3) %>" type="audio/mp3">
		  <source src="<%= track.file.url(:ogg) %>" type="audio/ogg">
	      </audio>
	    </td>
	    <% end %>
	</tbody>
      </table>
    </div>
    <div class="description"><%= markdown(@release.description).html_safe %></div>
  </div>
  <div class="btn-ctrls">
    <% if session[:user_id] %>
    <%= link_to 'Edit', edit_release_path(@release), :class => 'btn' %> |
    <%= link_to 'Delete', @release, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn' %>
    <% end %>
    <%= link_to 'Back', releases_path, :class => 'btn' %>
  </div>
</div>
<% end %>